controllers/UserController.php
<?php

namespace app\controllers;

use app\models\Accessories;
use app\models\Branch;
use app\models\ChatMessage;
use app\models\City;
use app\models\Company;
use app\models\Faq;
use app\models\forms\AvatarForm;
use app\models\forms\CityCashForm;
use app\models\forms\OrderForm;
use app\models\ImageCompany;
use app\models\TemplateFields;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\forms\ResetPasswordForm;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'except' => ['edit-city', 'redirect', 'faq', 'send-request', 'get-subcategories', 'get-params', 'get-params-data'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->identity->isSuperAdmin() == false){
            if(Yii::$app->user->identity->company->type == Company::TYPE_PROVIDER){
                $this->view->params['left'] = true;
                $this->view->params['left-content'] = $this->renderAjax('@app/views/user/left-profile');
            }

            $searchModel = new UserSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $dataProvider->query->andWhere(['company_id' => Yii::$app->user->identity->company_id]);
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return array
     */
    public function actionEditCity()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $model = new CityCashForm();

        if($request->isGet){
            return [
                'title'=> "",
                'content'=>$this->renderAjax('edit-city', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
            ];
        }else if($model->load($request->post()) && $model->saveInCash()){
            return [
                'title'=> "",
                'content'=> "<span class='text-success'>Сохранение <i class='fa fa-spinner fa-spin'></i></span><script>window.location.reload();</script>",
                'footer'=> '',
            ];
        }else{
            return [
                'title'=> "",
                'content'=>$this->renderAjax('edit-city', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
            ];
        }
    }

    /**
     *
     */
    public function actionProfile()
    {
        $this->view->params['left'] = true;
        $this->view->params['left-content'] = $this->renderAjax('left-profile');
        $request = Yii::$app->request;


        /** @var Company $model */
        $model = Yii::$app->user->identity->company;
        $modelUser = Yii::$app->user->identity;

        if($model->load($request->post()) && $model->validate()){

            $model->file = UploadedFile::getInstance($model, 'file');

            $model->save(false);

            Yii::$app->session->setFlash('success', 'Изменения сохранены');

            if($modelUser->load($request->post()) && $modelUser->save()){

            }

            return $this->render('profile', [
                'model' => $model,
                'modelUser' => $modelUser,
            ]);
        }

        return $this->render('profile', [
            'model' => $model,
            'modelUser' => $modelUser,
        ]);
    }


    /**
     *
     */
    public function actionDescription()
    {
        $this->view->params['left'] = true;
        $this->view->params['left-content'] = $this->renderAjax('left-profile');
        $request = Yii::$app->request;

        /** @var Company $model */
        $model = Yii::$app->user->identity->company;

        if($model->load($request->post()) && $model->save()){

            Yii::$app->session->setFlash('success', 'Изменения сохранены');

            return $this->render('description', [
                'model' => $model,
            ]);
        }

        return $this->render('description', [
            'model' => $model,
        ]);
    }

    /**
     *
     */
    public function actionGallery()
    {
        $this->view->params['left'] = true;
        $this->view->params['left-content'] = $this->renderAjax('left-profile');
        $request = Yii::$app->request;

        /** @var Company $model */
        $model = Yii::$app->user->identity->company;

        return $this->render('gallery', [
            'model' => $model,
        ]);
    }


    public function actionDeleteCompanyPhoto($id = null)
    {
        $request = Yii::$app->request;
        Yii::$app->response->format = Response::FORMAT_JSON;

        $model = ImageCompany::findOne($id);

        if($model){
            $model->delete();
        }

        return [
            'forceReload' => '#pjax-gallery-container',
            'forceClose' => true,
        ];
    }

    public function actionUploadCompanyPhoto($companyId)
    {
        $request = Yii::$app->request;
        Yii::$app->response->format = Response::FORMAT_JSON;

        if ($request->isPost) {
            return [
                'forceReload' => '#pjax-gallery-container',
                'forceClose' => true,
            ];
        }

        return [
            'title' => "Загрузить файл",
            'content' => $this->renderAjax('upload-image', [
                'companyId' => $companyId,
            ]),
            'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                Html::button('Готово', ['class' => 'btn btn-primary', 'type' => "submit"])
        ];
    }

    public function actionUploadCompanyPhotoTotal($companyId = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $fileName = Yii::$app->security->generateRandomString();
        if (is_dir('uploads') == false) {
            mkdir('uploads');
        }
        $uploadPath = 'uploads';
        if (isset($_FILES['file'])) {
            $file = UploadedFile::getInstanceByName('file');
            $path = $uploadPath . '/' . $fileName . '.' . $file->extension;

            $name = "{$file->baseName}.{$file->extension}";


            if ($file->saveAs($path)) {
//
                $file = new ImageCompany([
                    'company_id' => $companyId,
                    'name' => $name,
                    'path' => $path,
                    'created_at' => date('Y-m-d H:i:s'),
                ]);
                $file->save(false);

                return $path;
            }
        }
    }


    /**
     *
     */
    public function actionFaq()
    {
        if(Yii::$app->user->isGuest == false){
            $this->view->params['left'] = true;
            $this->view->params['left-content'] = $this->renderAjax('left-profile');
        }

        $faqs = Faq::find();


        if(Yii::$app->user->isGuest){
            $faqs->andWhere(['type' => Faq::TYPE_UNREGISTERED]);
        } else {
            if(Yii::$app->user->identity->company->type == Company::TYPE_BUYER){
                $faqs->andWhere(['type' => Faq::TYPE_BUYER]);
            } elseif(Yii::$app->user->identity->company->type == Company::TYPE_PROVIDER) {
                $faqs->andWhere(['type' => Faq::TYPE_PROVIDER]);
            }
        }

        $faqs = $faqs->all();

        return $this->render('faq', [
            'faqs' => $faqs,
        ]);
    }

    /**
     *
     */
    public function actionTariff()
    {
        $this->view->params['left'] = true;
        $this->view->params['left-content'] = $this->renderAjax('left-profile');


        return $this->render('tariff', [
        ]);
    }

    /**
     *
     */
    public function actionIdea()
    {
        $this->view->params['left'] = true;
        $this->view->params['left-content'] = $this->renderAjax('left-profile');


        return $this->render('idea', [
        ]);
    }

    /**
     *
     */
    public function actionQuestion()
    {
        $request = Yii::$app->request;
        $this->view->params['left'] = true;
        $this->view->params['left-content'] = $this->renderAjax('left-profile');

        if($request->isPost){
            Yii::$app->session->addFlash('success', 'Письмо успешно отправлено');

            $subject = isset($_POST['subject']) ? $_POST['subject'] : null;

views/user/_columns.php
<?php

use app\models\Company;
use app\models\User;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
//         [
//         'class'=>'\kartik\grid\DataColumn',
//         'attribute'=>'id',
//
//     ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'email',
        'width' => '200px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'fio',
        'label' => 'ФИО',
        'content' => function($model){
            return $model->fio;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute' => 'company_id',
        'value' => 'company.name',
        'filterType' => \kartik\select2\Select2::className(),
        'filterWidgetOptions' => [
            'data' => ArrayHelper::map(Company::find()->all(), 'id', 'name'),
            'pluginOptions' => ['allowClear' => true, 'placeholder' => 'Выберите компани'],
        ],
        'visible' => Yii::$app->user->identity->isSuperAdmin(),
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'company_type',
       'content' => function($model){
            $type = ArrayHelper::getValue(Company::find()->where(['id' => $model->company_id])->one(),'type');
           if($type === 1){
               return 'Компания';
           }elseif($type === 0){
               return 'Покупатель';
           }else{
               return 'Суперкомпания';
           }
        },
        'visible' => Yii::$app->user->identity->company->type != Company::TYPE_PROVIDER,
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'is_deletable',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'template' => '{update} {delete}',
//        'visible' => Yii::$app->user->identity->isSuperadmin(),
        'buttons' => [
            'delete' => function ($url, $model) {
                return Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-cancel'=>'Отмена',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данного пользователя?'
                ]);
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="fa fa-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Изменить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                ]);
            },
        ],
        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Сохранить', 'data-toggle'=>'tooltip'],
    ],

];   

views/user/accessories.php
<?php

use app\models\User;
use yii\bootstrap\Modal;
use yii\widgets\ActiveForm;

/**
 * @var $model User
 */


$this->title = 'Основные услуги';

$accessories = \app\models\Accessories::find()->where(['accessories_id' => null])->all();

\johnitvn\ajaxcrud\CrudAsset::register($this);

?>

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Основные услуги</h4>
    </div>
    <div class="card-content">
        <div class="card-body">
            <?php $form = ActiveForm::begin() ?>
            <?php foreach ($accessories as $accessory): ?>
                <div class="card shadow-none bg-transparent border-primary" style="border: none !important;">
                    <div class="card-body">
                        <h4 class="card-title"><?= $accessory->name ?></h4>
                        <?php
                            $childAccessories = \app\models\Accessories::find()->where(['accessories_id' => $accessory->id])->all();
                        ?>
                        <div class="row">
                            <?php foreach ($childAccessories as $childAccessory): ?>
                                <?php
                                    $checked = false;

                                    $data = json_decode($model->accessories);

                                    if(is_array($data)){
                                        $checked = in_array($childAccessory->id, $data);
                                    }
                                ?>
                                <div class="col-md-3"><?=$childAccessory->name?><input name="AccessoriesArr[<?=$childAccessory->id?>]" <?=($checked ? "checked='checked'" : null)?> type="checkbox" style="margin-left: 5px; margin-bottom: 25px;"></div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            <?= \yii\helpers\Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
            <?php ActiveForm::end() ?>
        </div>
    </div>
</div>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => ['class' => 'modal-super-slg'],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/user/description.php
<?php

use app\models\City;
use app\models\Company;
use app\models\Metro;
use app\models\User;
use yii\bootstrap\Modal;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

/**
 * @var $model User
 */


$this->title = 'Описание';

\johnitvn\ajaxcrud\CrudAsset::register($this);

?>

<style>
    #cke_21 {
        display: none;
    }
</style>

    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Описание</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <?php $form = ActiveForm::begin() ?>

                <div class="row">
                    <div class="col-md-12">

                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field($model, 'description')->widget(\mihaildev\ckeditor\CKEditor::class, [
                                    'editorOptions' => [
                                        'preset' => 'basic',
                                    ],
                                ])->label(false)?>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-12">
                                <?= \yii\helpers\Html::submitButton('<i class="fa fa-check"></i> Сохранить', ['class' => 'btn btn-success']) ?>
                            </div>
                        </div>

                    </div>
                </div>

                <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => ['class' => 'modal-super-slg'],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/user/edit-city.php
<?php
use app\models\City;
use app\models\Metro;
use yii\helpers\ArrayHelper;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\forms\CityCashForm */
/* @var $form yii\widgets\ActiveForm */

$citiesData = [];
$cities = City::find()->joinWith(['region'])->andWhere(['region.name' => 'Санкт-Петербург и Ленинградская область'])->all();

foreach ($cities as $city){
    $citiesData[$city->id] = $city->name;
}

?>


<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'city')->widget(\kartik\select2\Select2::class, [
        'data' => $citiesData,
        'options' => [
            'placeholder' => 'Выберите'
        ],
    ]) ?>

    <div id="metro-wrapper"<?=(Metro::find()->where(['city_id' => $model->city])->count() == 0 ? "style='display: none';" : null)?>>
        <?= $form->field($model, 'metro')->dropDownList($model->city ? ArrayHelper::map(Metro::find()->where(['city_id' => $model->city])->all(), 'id', 'name') : [], ['prompt' => 'Выберите']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php

$script = <<< JS
$("#citycashform-city").change(function(){
    $.get("/city/get-dropdown-data-metro?id="+$(this).val(), function(response){
        if(response.count > 0){
            $("#citycashform-metro").html(response.text);
            $("#metro-wrapper").show();
        } else {
            $("#citycashform-metro").val(null);
            $("#metro-wrapper").hide();
        }
    });
});
JS;

$this->registerJs($script, View::POS_READY);

?>

views/user/faq.php
<?php

/** @var $this \yii\web\View */
use yii\bootstrap\Modal;

/** @var $faqs app\models\Faq[] */

$this->title = 'FAQ';

\johnitvn\ajaxcrud\CrudAsset::register($this);

?>


<div class="collapse-margin collapse-icon mt-2" id="faq-payment-qna">
    <?php $counter = 1; foreach ($faqs as $faq): ?>

        <div class="card">
            <div class="card-header collapsed" id="paymentOne" role="button" data-target="#faq-payment-<?=$counter?>" aria-expanded="false" onclick="$(this).parent().find('.collapse').slideToggle();" style="cursor: pointer;">
                <span class="lead collapse-title"><?= $faq->name ?></span>
            </div>

            <div id="faq-payment-<?=$counter?>" class="collapse" aria-labelledby="paymentOne" data-parent="#faq-payment-qna" style="">
                <div class="card-body">
                    <?= $faq->content ?>
                </div>
            </div>
        </div>

        <?php $counter++; ?>
    <?php endforeach; ?>
</div>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => ['class' => 'modal-super-slg'],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/user/gallery.php
<?php

use app\models\ImageCompany;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\Pjax;

/** @var $this \yii\web\View */

$this->title = "Галерея";

\johnitvn\ajaxcrud\CrudAsset::register($this);

?>

<div class="card">
    <div class="card-content">
        <div class="card-body">
            <?= Html::a('Добавить фото', ['user/upload-company-photo', 'companyId' => Yii::$app->user->identity->company_id], ['class' => 'btn btn-primary', 'role' => 'modal-remote']) ?>
        </div>
    </div>
</div>

<?php Pjax::begin(['id' => 'pjax-gallery-container', 'enablePushState' => false]) ?>
    <div class="clearfix">
        <?php foreach (ImageCompany::find()->where(['company_id' => Yii::$app->user->identity->company_id])->all() as $model): ?>
            <div style="width: 300px; height: 300px; margin: 8px; float: left; position: relative;">
                <a class="image-popup-vertical-fit" href="/<?=$model->path?>"><img src="/<?=$model->path?>" alt="" style="width: 100%; height: 100%; object-fit: cover; position: absolute;"></a>
                <?= Html::a('<i class="feather icon-trash-2"></i>', ['user/delete-company-photo', 'id' => $model->id], [
                    'class' => 'btn btn-danger btn-sm',
                    'style' => 'position: absolute; top: 10px; right: 15px; font-size: 14px;',
                    'onclick' => 'event.preventDefault(); if(confirm("Вы уверены что хотите удалить изображение?")){ var url = $(this).attr("href"); $.get(url, function(response){ $.pjax.reload("#pjax-gallery-container"); }); }',
                ]) ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php Pjax::end() ?>

<?php Modal::begin([
    "id" => "ajaxCrudModal",
    'options' => ['class' => 'modal-super-slg'],
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>


<?php

$script = <<< JS
	$('.image-popup-vertical-fit').magnificPopup({
		type: 'image',
		closeOnContentClick: true,
		mainClass: 'mfp-img-mobile',
		 closeOnContentClick: false,
	});

$(document).on('pjax:complete' , function(event) {
	$('.image-popup-vertical-fit').magnificPopup({
		type: 'image',
		closeOnContentClick: true,
		mainClass: 'mfp-img-mobile',
		 closeOnContentClick: false,
	});
});
JS;

$this->registerJs($script, \yii\web\View::POS_READY);

?>

views/user/idea.php
<?php

use yii\widgets\ActiveForm;

/** @var $this \yii\web\View */

$this->title = 'Предложить идею';

?>

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Предложить идею</h4>
    </div>
    <div class="card-content">
        <div class="card-body">
            <?php $form = ActiveForm::begin() ?>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Заголовок</label>
                        <?= \yii\helpers\Html::textInput('subject', '', ['class' => 'form-control']) ?>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Идея</label>
                        <?= \yii\helpers\Html::textarea('content', '', ['class' => 'form-control']) ?>
                    </div>
                </div>
                <div class="col-md-12">
                    <?= \yii\helpers\Html::submitButton('Отправить', ['class' => 'btn btn-success']) ?>
                </div>
            </div>

            <?php ActiveForm::end() ?>
        </div>
    </div>
</div>

views/user/left-profile.php
<?php

use yii\helpers\Url;

/**
 * @param string $url
 * @return string
 */
function activeClass($url)
{
    $url = explode('/', $url);

    if(count($url) != 2)
        return null;

    $controllerId = $url[0];
    $actionId = $url[1];

    return Yii::$app->controller->id == $controllerId && Yii::$app->controller->action->id == $actionId ? " active" : null;
}


?>
<?php if(Yii::$app->user->isGuest == false): ?>
    <?php if(Yii::$app->user->identity->company->type == \app\models\Company::TYPE_PROVIDER): ?>
        <li class="nav-item<?=activeClass('user/profile')?>">
            <a href="<?= Url::toRoute(['/user/profile']) ?>"><span class="menu-title">Администратор</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/description')?>">
            <a href="<?= Url::toRoute(['/user/description']) ?>"><span class="menu-title">Описание</span></a>
        </li>
        <div class="hidden">
            <li class="nav-item">
                <a href="<?= Url::toRoute(['/user/requisites']) ?>"><span class="menu-title">Реквизиты</span></a>
            </li>
            <li class="nav-item">
                <a href="<?= Url::toRoute(['/branch/work-hours']) ?>"><span class="menu-title">Часы работы</span></a>
            </li>
            <li class="nav-item">
                <a href="<?= Url::toRoute(['/action']) ?>"><span class="menu-title">Соцсети</span></a>
            </li>
            <li class="nav-item">
                <a href="<?= Url::toRoute(['/user/accessories']) ?>"><span class="menu-title">Основные услуги</span></a>
            </li>
            <li class="nav-item">
                <a href="<?= Url::toRoute(['/user/accessories-other']) ?>"><span class="menu-title">Другие услуги</span></a>
            </li>
            <li class="nav-item">
                <a href="<?= Url::toRoute(['/price/index']) ?>"><span class="menu-title">Мои прайсы</span></a>
            </li>
        </div>
        <li class="nav-item<?=activeClass('user/accessories')?>">
            <a href="<?= Url::toRoute(['/user/accessories']) ?>"><span class="menu-title">Услуги</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/accessories-other')?>">
            <a href="<?= Url::toRoute(['/user/accessories-other']) ?>"><span class="menu-title">Другие услуги</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/gallery')?>">
            <a href="<?= Url::toRoute(['/user/gallery']) ?>"><span class="menu-title">Галерея</span></a>
        </li>
        <li class="nav-item<?=activeClass('branch/index')?>">
            <a href="<?= Url::toRoute(['/branch/index']) ?>"><span class="menu-title">Филиалы</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/index')?>">
            <a href="<?= Url::toRoute(['/user/index']) ?>"><span class="menu-title">Пользователи</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/tariff')?>" style="display: none;">
            <a href="<?= Url::toRoute(['/user/tariff']) ?>"><span class="menu-title">Тарифы</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/faq')?>">
            <a href="<?= Url::toRoute(['/user/faq']) ?>"><span class="menu-title">FAQ</span></a>
        </li>
    <?php else: ?>
        <li class="nav-item<?=activeClass('user/profile')?>">
            <a href="<?= Url::toRoute(['/user/profile']) ?>"><span class="menu-title">Профиль</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/my-providers')?>">
            <a href="<?= Url::toRoute(['/user/my-providers']) ?>"><span class="menu-title">Избранное</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/tariff')?>" style="display: none;">
            <a href="<?= Url::toRoute(['/user/tariff']) ?>"><span class="menu-title">Тарифы</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/faq')?>">
            <a href="<?= Url::toRoute(['/user/faq']) ?>"><span class="menu-title">FAQ</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/question')?>">
            <a href="<?= Url::toRoute(['/user/question']) ?>"><span class="menu-title">Задать вопрос</span></a>
        </li>
        <li class="nav-item<?=activeClass('user/accessories-other')?>">
            <a href="<?= Url::toRoute(['site/logout']) ?>" data-method="POST"><span class="menu-title">Выход</span></a>
        </li>
    <?php endif; ?>
<?php endif; ?>

views/user/reset-password-form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\forms\ResetPasswordForm */
/* @var $form ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'newPassword') ?>
<?= $form->field($model, 'repeatPassword') ?>

<?php if(!Yii::$app->request->isAjax): ?>
    <div class="form-group">
        <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary']) ?>
    </div>
<?php endif; ?>

<?php ActiveForm::end(); ?>

views/user/upload-image.php
<?php
use app\models\File;
use app\models\FileAwait;
use kato\DropZone;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ImageCompany */
/* @var $form yii\widgets\ActiveForm */
/* @var $companyId int */


?>


<div class="user-form">
    <?php ActiveForm::begin() ?>

    <?= DropZone::widget([
        'id'        => 'dzImage',
        'uploadUrl' => Url::toRoute([ 'user/upload-company-photo-total', 'companyId' => $companyId]),
        'dropzoneContainer' => 'dz-container-images', // <-- уникальные dropzoneContainer
        'previewsContainer' => 'preview-images', // <-- уникальные previewsContainer
        'options' => [
            'dictDefaultMessage' => 'Нажмите чтобы загрузить файлы'
        ],
    ]);?>

    <?php ActiveForm::end() ?>
</div>