controllers/ReportController.php
<?php

namespace app\controllers;

use app\models\Accessories;
use app\models\ActionSearch;
use app\models\Advert;
use app\models\Branch;
use app\models\BranchSearch;
use app\models\ChatMessage;
use app\models\City;
use app\models\Company;
use app\models\forms\ReportFilterForm;
use app\models\ImageCompany;
use app\models\Metro;
use app\models\Price;
use app\models\PriceCity;
use app\models\PriceMetro;
use app\models\TemplateFields;
use app\models\User;
use PHPUnit\Framework\Constraint\Count;
use Yii;
use app\models\PriceParam;
use app\models\PriceParamSearch;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * ReportController implements the CRUD actions for PriceParam model.
 */
class ReportController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
//            'access' => [
//                'class' => \yii\filters\AccessControl::className(),
//                'rules' => [
//                    [
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
//                ],
//            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all PriceParam models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(Yii::$app->user->isGuest == false){
            if(Yii::$app->user->identity->company->type == Company::TYPE_PROVIDER){
                return $this->redirect(['price/index']);
            }
        }

//        $accessories = Accessories::find()->where(['is', 'accessories_id', null])->andWhere(['is_main' => true])->all();
        $accessories = Accessories::find()->where(['is', 'accessories_id', null])->all();


        $searchModel = new ReportFilterForm();
//        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $searchModel->load(Yii::$app->request->queryParams);

        if($searchModel->accessoryId == null){
            if(isset($accessories[0])){
                $searchModel->accessoryId = $accessories[0]->id;
            }
        }


        return $this->render('index', [
            'searchModel' => $searchModel,
//            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all PriceParam models.
     * @return mixed
     */
    public function actionParams($headerAccessoryId = null)
    {
        $searchModel = new ReportFilterForm();
        $searchModel->load(Yii::$app->request->queryParams);
        $this->view->params['filterEnable'] = true;
        $this->view->params['filterActive'] = true;


        $cityFilterValue = Yii::$app->session->get('user__city');
        $metroFilterValue = Yii::$app->session->get('user__metro');

        if(isset($_GET['Fld'])){
            foreach ($_GET['Fld'] as $fldName => $fldValue){
                if($fldValue){
                    $this->view->params['filterActive'] = true;
                }
            }
        }

        if($headerAccessoryId == null){
            $headerAccessories = Accessories::find()->where(['is', 'accessories_id', null])->andFilterWhere(['id' => $headerAccessoryId])->all();
            if(isset($headerAccessories[0])){
                $headerAccessoryId = $headerAccessories[0]->id;
                if($searchModel->accessoryId == null){
                    $kings = Accessories::find()->where(['accessories_id' => $headerAccessories[0]->id])->all();
                    if(isset($kings[0])){
                        $searchModel->accessoryId = $kings[0]->id;
                    }
                }
            }
        }

        $pricesPks = [];

        $query = null;

        if($searchModel->accessoryId){
            $pricesPks = ArrayHelper::getColumn(Accessories::find()->where(['accessories_id' => $searchModel->accessoryId])->all(), 'id');
            $pricesModel = Price::find()
                ->where(['accessory_id' => $pricesPks])
                ->andWhere(['order_status' => Price::ORDER_STATUS_PUBLISHED])
                ->andWhere(['!=', 'price.company_id', 1])
                ->joinWith(['priceCities', 'priceMetros', 'branch']);
//                ->andFilterWhere(['price_city.city_id' => Yii::$app->session->get('user__city')])


//            if(isset($_GET['FldPrice'])) {
            if($cityFilterValue){
                $pricesModel->andFilterWhere(['branch.city_id' => $cityFilterValue]);
//                    $cityFilterValue = $_GET['FldPrice']['cities'];
                if($cityFilterValue){
//                    $this->view->params['filterActive'] = true;
                }
            }
            if($metroFilterValue){
                $pricesModel->andFilterWhere(['branch.metro_id' => $metroFilterValue]);
//                    $metroFilterValue = $_GET['FldPrice']['metro'];
                if($metroFilterValue){
//                    $this->view->params['filterActive'] = true;
                }
            }
//            }

            $pricesModel = $pricesModel->all();


//            VarDumper::dump([$cityFilterValue, $metroFilterValue], 10, true);
//            exit;





            $pricesPks = ArrayHelper::getColumn($pricesModel,'id');



           // \yii\helpers\VarDumper::dump($pricesPks, 10, true);
           // exit;

            $params = PriceParam::find()
                ->select('price_param.*, company.name as company_name, company.rate_id as company_rate_id')
                ->where(['price_id' => $pricesPks])
                ->andWhere(['!=', 'company.type', Company::TYPE_BUYER])
                ->joinWith('price.accessory as accessory')
                ->joinWith('price.branch as branch')
                ->joinWith('price.company as company');


            if(Yii::$app->user->isGuest){
                $params->andWhere(['!=', 'company.rate_id', 0]);
            } else {
                if(Yii::$app->user->identity->company->type == Company::TYPE_BUYER){
                    if(Yii::$app->user->identity->company->rate_id !== Company::RATE_BRANCH){
                        $params->andWhere(['!=', 'company.rate_id', 0]);
                    }
                }
            }



            if(isset($_GET['Fld'])){
//                VarDumper::dump($_GET['Fld'], 10, true);
//                exit;
                foreach ($_GET['Fld'] as $id => $value){
                    if($value == null) continue;
                    if($value != -1){
                        $params->andWhere(['like', 'params', '"'.$id.'":"'.$value.'"']);
                    } else {
                        $params->andWhere(['like', 'params', '"'.$id.'":""']);
                    }
                }
            }

            $query = clone $params;



//            echo $params->createCommand()->getRawSql();
//            exit;


            $params = $params->asArray()->all();

//            VarDumper::dump($params, 10, true);
//            exit;



        $childAccess = Accessories::find()->where(['accessories_id' => $searchModel->accessoryId])->one();


        if($childAccess){
            /** @var TemplateFields[] $fields */
            $fields = TemplateFields::find()->where(['accessories_id' => $childAccess->id])->orderBy('sort asc')->all();


                        foreach ($fields as $field){


                            $label = $field->label;

                            if(strlen($label) > 10){
                                $label = iconv_substr($label, 0, 10, "UTF-8" ).'...';
                            }

                            $attributes['attr_'.$field->id] = [
                                'asc' => ['attr_'.$field->id => SORT_ASC, 'attr_'.$field->id => SORT_ASC],
                                'desc' => ['attr_'.$field->id => SORT_DESC, 'attr_'.$field->id => SORT_DESC],
                                'default' => SORT_DESC,
                                'label' => 'Name',
                            ];
                        }

                $dataProvider = new ArrayDataProvider([
                        'allModels' => $params,
                        'sort' => [
                            'attributes' => $attributes,
                        ],
                    ]);
                // $dataProvider->setModels($params);
            } else {
                $fields = [];

                $dataProvider = new ArrayDataProvider([
                    'allModels' => [],
                ]);
            }
        } else {
                $fields = [];

                $dataProvider = new ArrayDataProvider([
                    'allModels' => [],
                ]);
        }
        // \yii\helpers\VarDumper::dump($dataProvider->models, 10, true);
        // exit;





        // \yii\helpers\VarDumper::dump($query->createCommand()->getRawSql(), 10, true);
        // exit;

        return $this->render('params', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'pricesPks' => $pricesPks,
            'query' => $query,
            'headerAccessoryId' => $headerAccessoryId,
            'cityFilterValue' => $cityFilterValue,
            'metroFilterValue' => $metroFilterValue,
        ]);
    }

    public function actionBranchUserChat($providerId)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $users = User::find()->where(['company_id' => $providerId])->all();
        $bracnhes = Branch::find()->where(['id' => ArrayHelper::getColumn($users, 'branch_id')])->all();


        return [
            'title'=> "",
            'content'=>$this->renderAjax('branches_list', [

views/report/_params_search.php
<?php

use yii\widgets\ActiveForm;
use app\models\TemplateFields;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/** @var $this \yii\web\View */
/** @var $fields TemplateFields */

?>

<div class="container">
    <?php $searchForm = ActiveForm::begin(['id' => 'search-form', 'method' => "GET"]) ?>
    <div class="row">
        <?php foreach ($fields as $field): ?>

            <?php if($field->type != TemplateFields::TYPE_DROPDOWN) continue; ?>

            <?php


            $fldValue = null;

            if(isset($_GET['Fld'])){
                $fldValue = ArrayHelper::getValue($_GET['Fld'], $field->id);
            }

            $parent = $field->parent;

            $disabled = false;

            if($parent){
                $disabled = true;
                if(isset($_GET['Fld'])){
                    if(isset($_GET['Fld'][$parent->id])){
                        if($_GET['Fld'][$parent->id]){
                            $disabled = false;
                        }
                    }
                }
            }

//                            \yii\helpers\VarDumper::dump($_GET, 10, true);

            $data = explode(',', $field->data);

           $data = array_filter($data, function($value) use ($query, $field, $pricesPks, $parent, $fldValue){

               $query = clone $query;

               if($parent){
                   $filterValue = null;

                   if(isset($_GET['Fld'])){
                       if(isset($_GET['Fld'][$parent->id])){
                           if($_GET['Fld'][$parent->id]){
                               $filterValue = $_GET['Fld'][$parent->id];
                           }
                       }
                   }


                   $prices = $query->andWhere(['like', 'params', '"'.$field->id.'":"'.$value.'"'])->andWhere(['like', 'params', '"'.$parent->id.'":"'.$filterValue.'"'])->count();
               } else {
                   $prices = $query->andWhere(['like', 'params', '"'.$field->id.'":"'.$value.'"'])->count();
               }

               if($fldValue){
                   return $fldValue == $value;
               }


//                 $prices = \app\models\PriceParam::find()->where(['like', 'params', '"'.$field->id.'":"'.$value.'"'])->andWhere(['price_id' => $pricesPks, 'company.id' => $providerId])->count();

               return $prices > 0;
           });

            $data = array_combine($data,$data);

           $data = array_filter($data, function($model){
                return $model != "Нет" && $model != "";
           });

           // array_walk($data, function(&$model){
           //     if($model == null){
           //         $model = 'Нет';
           //     }
           // });

        // foreach($data as $key => $value)
        // {
        //     if($value == null){
        //         unset($data[$key]);
        //         $data[null] = "Нет";
        //     }
        // }

           $data[-1] = "Нет";

            ?>

            <div class="col-md-12">
                <div class="form-group">
                    <label for=""><?=$field->label?> <?= $field->hint_title ? Html::a('<i class="fa fa-question-circle"></i>', '#', ['title' => $field->hint_title."\n".$field->hint_content, 'style' => 'font-size: 16px;']) : null ?></label>
                    <?= Html::dropDownList("Fld[{$field->id}]", $fldValue, $data, ['class' => 'form-control', 'disabled' => $disabled, 'prompt' => 'Выберите']) ?>
                </div>
            </div>

        <?php endforeach; ?>




    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            echo Html::a('Очистить', '#', ['class' => 'btn btn-primary', 'style' => 'margin-top: 20px; background:009fe3!important;',
                'onclick' => 'event.preventDefault(); $("#search-form input, #search-form select").each(function(){
                    $(this).val(null);
                });
                $("#search-form").submit();
                '
                ])
            ?>
            <?php 
            // echo Html::a('Режим PRO', '#', ['class' => 'btn btn-primary', 'style' => 'margin-top: 20px; width: 144px; background: #e6007e!important;',
            //     'onclick' => 'event.preventDefault(); $("#search-form input, #search-form select").each(function(){
                
            //         if($(this).attr("name") != "headerAccessoryId" && $(this).attr("name") != "accessoryId"){
            //             $(this).val(null);
            //         }
                
            //     });
                
                
                
            //     $("#search-form").submit();
            //     '
            // ])
            ?>
            <?php
//                echo Html::submitButton('Поиск', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px;', 'onclick' => '$("#search-form").attr("action", "/report/params");'])
            ?>
        </div>
    </div>
    <?php ActiveForm::end() ?>
</div>


<?php

$script = <<< JS

$("#search-form input, #search-form select").change(function(){
    ym(76222834,'reachGoal','site prices (use left filters)');
    $("#search-form").submit();
});

JS;

$this->registerJs($script, \yii\web\View::POS_READY);

?>

views/report/_search.php
<?php

use yii\widgets\ActiveForm;
use app\models\TemplateFields;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/** @var $this \yii\web\View */
/** @var $fields TemplateFields */

?>

<div class="container">
    <?php $searchForm = ActiveForm::begin(['id' => 'search-form', 'method' => "GET"]) ?>
    <div class="row">
        <?php foreach ($fields as $field): ?>

            <?php if($field->type != TemplateFields::TYPE_DROPDOWN) continue; ?>

            <?php

            $data = explode(',', $field->data);

            $data = array_filter($data, function($value) use ($query, $field, $pricesPks, $providerId){

                $query = clone $query;

//                $prices = \app\models\PriceParam::find()->where(['like', 'params', '"'.$field->id.'":"'.$value.'"'])->andWhere(['price_id' => $pricesPks, 'company.id' => $providerId])->joinWith('price.company as company')->count();
                $prices = $query->andWhere(['like', 'params', '"'.$field->id.'":"'.$value.'"'])->andWhere(['price_id' => $pricesPks, 'company.id' => $providerId])->joinWith('price.company as company')->count();

                return $prices > 0;
            });


            $fldValue = null;

            if(isset($_GET['Fld'])){
                $fldValue = ArrayHelper::getValue($_GET['Fld'], $field->id);
            }

            $data = array_combine($data,$data);

            $data[-1] = "Нет";

            ?>

            <div class="col-md-12">
                <div class="form-group">
                    <label for=""><?=$field->label?> <?= $field->hint_title ? Html::a('<i class="fa fa-question-circle"></i>', '#', ['title' => $field->hint_title."\n".$field->hint_content, 'style' => 'font-size: 16px;']) : null ?></label>
                    <?= Html::dropDownList("Fld[{$field->id}]", $fldValue, $data, ['class' => 'form-control', 'prompt' => 'Выберите']) ?>
                </div>
            </div>



        <?php endforeach; ?>

        <div class="col-md-12 hidden">
            <div class="form-group">
                <label for="">Город</label>
                <?php

                $citiesData = [];



                foreach(\app\models\City::find()->where(['city.id' => $searchCitiesPks])->joinWith(['region'])->andWhere(['region.name' => 'Санкт-Петербург и Ленинградская область'])->all() as $city){
                    if($city->region){
                        $citiesData[$city->id] = $city->name;
                    } else {
                        $citiesData[$city->id] = $city->name;
                    }
                }


                ?>
                <?= \kartik\select2\Select2::widget([
                    'name' => 'FldPrice[cities]',
                    'data' => $citiesData,
                    'value' => $cityFilterValue,
                    'options' => [
                        'placeholder' => 'Выберите',
                    ],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                    'pluginEvents' => [
                        'change' => 'function(){ $("#search-form").submit(); }'
                    ],
                ]) ?>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <label for="">Метро</label>
                <?php

                $metroData = [];

                if($cityFilterValue){
                    foreach(\app\models\Metro::find()->andWhere(['city_id' => $cityFilterValue])->all() as $metro){
                        if($metro->city){
                            $metroData[$metro->id] = $metro->city->name.' / '.$metro->name;
                        } else {
                            $citiesData[$metro->id] = $metro->name;
                        }
                    }
                }

                ?>
                <?= \kartik\select2\Select2::widget([
                    'name' => 'FldPrice[metro]',
                    'data' => $metroData,
                    'value' => $metroFilterValue,
                    'options' => [
                        'placeholder' => 'Выберите',
                    ],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                    'pluginEvents' => [
                        'change' => 'function(){ $("#search-form").submit(); }'
                    ],
                ]) ?>
            </div>
        </div>

<!--        'headerAccessoryId' => $headerAccessoryId,-->
<!--        'accessoryId' => $accessoryId,-->

        <div class="hidden">
            <input type="text" name="headerAccessoryId" value="<?= $headerAccessoryId ?>">
            <input type="text" name="accessoryId" value="<?= $accessoryId ?>">

        </div>

        <div class="col-md-2">
            <?= Html::a('Очистить', '#', ['class' => 'btn btn-primary', 'style' => 'margin-top: 20px;',
                'onclick' => 'event.preventDefault(); $("#search-form input, #search-form select").each(function(){
                
                    if($(this).attr("name") != "headerAccessoryId" && $(this).attr("name") != "accessoryId"){
                        $(this).val(null);
                    }
                
                });
                
                
                
                $("#search-form").submit();
                '
            ]) ?>
            <?php

//            echo Html::a('Режим PRO', '#', ['class' => 'btn btn-primary', 'style' => 'margin-top: 20px; width: 144px; background: #e6007e!important;',
//                'onclick' => 'event.preventDefault(); $("#search-form input, #search-form select").each(function(){
//
//                    if($(this).attr("name") != "headerAccessoryId" && $(this).attr("name") != "accessoryId"){
//                        $(this).val(null);
//                    }
//
//                });
//
//
//
//                $("#search-form").submit();
//                '
//            ])
            ?>
        </div>
    </div>
    <?php ActiveForm::end() ?>
</div>

<?php

$script = <<< JS

$("#search-form input, #search-form select").change(function(){
    $("#search-form").submit();
});


// $("[name='FldPrice[cities]']").change(function(){
//     $.get("/city/get-dropdown-data-metro?id="+$(this).val(), function(response){
//         if(response.count > 0){
//             $("[name='FldPrice[metro]']").html(response.text);
//         } else {
//             $("[name='FldPrice[metro]']").val(null);
//         }
//     });
// });

JS;

$this->registerJs($script, \yii\web\View::POS_READY);

?>

views/report/action.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AccessoriesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Акции';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>

<style>
    .label.label-success {
        background: #affad0;
        color: #26ab60;
        padding: 3px 5px;
        border-radius: 20px;
    }
    .card-body-content {
        padding: 1.5rem;
    }
</style>

<div class="row">
    <?php foreach ($dataProvider->models as $model): ?>
        <div class="col-md-3">
            <div class="card">
                <div class="card-content">
                    <div class="card-body" style="padding: 0;">
                        <img src="/<?= ($model->photo ? $model->photo : 'img/no-photo.png') ?>" style="width: 100%; height: 300px; object-fit: cover;"
                             alt="">
                        <div class="card-body-content">
                            <h4 class="card-title" style="font-weight: 700; font-size: 17px;"><?= $model->name ?></h4>
                            <span class="label label-success">+ <?= Yii::$app->formatter->asCurrency($model->price, 'rub') ?></span>
                            <span class="pull-right" style="font-size: 13px; color: #c42fbf; font-weight: 600;">До окончания 1 день</span>
                            <p style="margin-top: 10px;"><?php

                                echo "Москва";
                                ?> <img class="pull-right" src="/<?= ($model->company->avatar ? $model->company->avatar : '/img/no-photo.png') ?>" style="width: 30px; height: 30px; border-radius: 100%;"></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => [
        'class' => 'modal-slg'
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/report/branches_list.php
<?php

/** @var $this \yii\web\View */
/** @var $branches \app\models\Branch[] */

?>

    <h4>Выберите филиал</h4>
    <div class="list-group">
<?php foreach ($branches as $branch): ?>
        <?php
            $user = \app\models\User::find()->where(['branch_id' => $branch->id])->one();

            if($user == null)
                continue;
        ?>
        <a href="<?= \yii\helpers\Url::to(['user/chat', 'userId' => $user->id]) ?>" class="list-group-item list-group-item-action">
            <p style="margin-bottom: 2px;">
                <?= $branch->name ?>
            </p>
            <p class="text-secondary"><?php

                $data = [];

                if($branch->city_id){
                    $data[] = \yii\helpers\ArrayHelper::getValue($branch, 'city.name');
                }

                if($branch->metro_id){
                    $data[] = \yii\helpers\ArrayHelper::getValue($branch, 'metro.name');
                }

                echo implode(', ', $data);

                ?></p>
        </a>
<?php endforeach; ?>
    </div>

views/report/branches_list_single.php
<?php

/** @var $this \yii\web\View */
/** @var $branches \app\models\Branch[] */

?>

<h4>Выберите филиал</h4>
<div class="list-group">
    <?php foreach ($branches as $branch): ?>
        <?php
        $user = \app\models\User::find()->where(['branch_id' => $branch->id])->one();

        if($user == null)
            continue;
        ?>
        <a href="<?= \yii\helpers\Url::to(['report/single-page', 'headerAccessoryId' => $headerAccessoryId, 'accessoryId' => $accessoryId, 'providerId' => $providerId, 'FldPrice[cities]' => $branch->city_id, 'FldPrice[metro]' => $branch->metro_id]) ?>" class="list-group-item list-group-item-action">
            <p style="margin-bottom: 2px;">
                <?= $branch->name ?>
            </p>
            <p class="text-secondary"><?php

                $data = [];

                if($branch->city_id){
                    $data[] = \yii\helpers\ArrayHelper::getValue($branch, 'city.name');
                }

                if($branch->metro_id){
                    $data[] = \yii\helpers\ArrayHelper::getValue($branch, 'metro.name');
                }

                echo implode(', ', $data);

                ?></p>
        </a>
    <?php endforeach; ?>
</div>

views/report/gallery.php
<?php

use app\models\ImageCompany;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\Pjax;

/** @var $this \yii\web\View */

$this->title = "Галерея";

\johnitvn\ajaxcrud\CrudAsset::register($this);

?>

<?php Pjax::begin(['id' => 'pjax-gallery-container', 'enablePushState' => false]) ?>
    <div class="clearfix">
        <?php foreach ($images as $model): ?>
            <div style="width: 300px; height: 300px; margin: 8px; float: left; position: relative;">
                <a class="image-popup-vertical-fit" href="/<?=$model->path?>"><img src="/<?=$model->path?>" alt="" style="width: 100%; height: 100%; object-fit: cover; position: absolute;"></a>
            </div>
        <?php endforeach; ?>
    </div>
<?php Pjax::end() ?>

<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>


<?php

$script = <<< JS
	$('.image-popup-vertical-fit').magnificPopup({
		type: 'image',
		closeOnContentClick: true,
		mainClass: 'mfp-img-mobile',
		 closeOnContentClick: false,
	});

$(document).on('pjax:complete' , function(event) {
	$('.image-popup-vertical-fit').magnificPopup({
		type: 'image',
		closeOnContentClick: true,
		mainClass: 'mfp-img-mobile',
		 closeOnContentClick: false,
	});
});
JS;

$this->registerJs($script, \yii\web\View::POS_READY);

?>

views/report/order-success.php
<?php

use app\models\Accessories;
use app\models\TemplateFields;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">

                </div>
                <div class="card-content">
                    <div class="card-body">

                        <p class="text-success" style="width: 100%; font-size: 22px; text-align: center;"><?= Yii::$app->session->getFlash('success') ?></p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/report/services.php
<?php

/** @var $this \yii\web\View */
/** @var $parentAccessories \app\models\Accessories[] */
/** @var $otherAccessories \app\models\Accessories[] */
/** @var $accessories \app\models\Accessories[] */
/** @var $company \app\models\Company */


$this->title = 'Услуги';

?>

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Основные услуги</h4>
    </div>
    <div class="card-content">
        <div class="card-body">
            <?php foreach ($parentAccessories as $parentAccessory): ?>
                <div class="card shadow-none bg-transparent border-primary" style="border: none !important;">
                    <div class="card-body">
                        <h4 class="card-title"><?= $parentAccessory->name ?></h4>
                        <div class="row">
                            <?php foreach ($accessories as $childAccessory): ?>
                                <?php

                                if($childAccessory->accessories_id != $parentAccessory->id){
                                    continue;
                                }

                                ?>
                                <div class="col-md-3"><?=$childAccessory->name?></div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Дополнительные услуги</h4>
    </div>
    <div class="card-content">
        <div class="card-body" style="font-size: 17px;">

            <?php

            $accessoriesHtml = [];

            foreach ($otherAccessories as $accessory){
                $accessoriesHtml[] = $accessory;
            }

            echo implode(', ', $accessoriesHtml);

            ?>
        </div>
    </div>
</div>